[package]
name = "zero-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29", default-features = false, features = ["signal", "term", "process", "fs"] }
once_cell = "1"

[features]
default = []

[dev-dependencies]
